### ISSUE TITLE
Correcting fixcase() name

### ISSUE THREAD

**Issue by a2geek** [bobbimanners/ProDOS-Utils#15]
Not a bug. But when using your app as a source of information, I was confused for a bit because `fixcase(...)` has parameter names cross-wired on usage. Specifically, the `vers` and `minvers` parameters are named one way but used another way.

For instance, the declaration [here](https://github.com/bobbimanners/ProDOS-Utils/blob/master/sortdir.c#L573):
```
void fixcase(char *in, char *out, uchar minvers, uchar vers, uchar len) {
```

And a usage [here](https://github.com/bobbimanners/ProDOS-Utils/blob/master/sortdir.c#L1277-L1278):
```
	fixcase(hdr->name, currdir,
	        hdr->vers, hdr->minvers, hdr->typ_len & 0x0f);
```

Thanks!

**Comment by bobbimanners** [comment]
Thanks for pointing this out.  I will fix this in due course!!

**Comment by bobbimanners** [comment]
Fixed.  This affects routines `fixcase()`, `uppercase()`, `lowercase()` and `initialcase()`.
